modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"
issueTrackerURL="https://github.com/salvadormg15/Rubber-Duck/issues"

[[mods]]
    modId="rubber_duck"
    version="2.5.0"
    displayName="Rubber Duck"
    displayURL="https://github.com/AtlasRiker/Rubber-Duck"
    logoFile="rubber_duck.png"
    authors="Atlas Riker, Salvadormg15"
    description="We just need a Rubber Duck to be happy"

[[dependencies.rubber_duck]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rubber_duck]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rubber_duck]]
    modId="curios"
    mandatory=true
    versionRange="[1.19.2-5.1.1.0,)"
    ordering="NONE"
    side="BOTH"